version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: outreach_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: outreach
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: outreach_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: outreach_redis
    ports:
      - "6379:6379"